In [22]:
import pandas as pd
import matplotlib.pyplot as plt

#Lendo df com Pandas
df = pd.read_csv(r"C:\Users\mathe\Documents\GitHub\Python\Dashboard Python\Municipios_brasileiros2020.csv")

In [26]:
#top 10 municipios com maior Pib

# Limpar e formatar a coluna de PIB
df['PIB'] = df['Produto Interno Brutoa preços correntes(1 000 R$)'].str.replace(' ', '').astype(int)

# Ordenar pelos maiores PIBs e selecionar o Top 10
top_10 = df.sort_values(by='PIB', ascending=False).head(10)

# Criar o gráfico de barras
plt.figure(figsize=(10, 6))
plt.barh(top_10['Municípios e respectivas\nUnidades da Federação'], top_10['PIB'], color='royalblue')
plt.xlabel('PIB (em milhares de R$)')
plt.ylabel('Municípios')
plt.title('Top 10 Municípios com Maior PIB no Brasil')
plt.gca().invert_yaxis()  # Inverte o eixo Y para mostrar o maior no topo
plt.show()

                                                        
#Distribuição de PIB por estado

#Concetração de Riqueza

#Comparação entre municipios

#Distribuição do Pib

C:\Users\mathe\AppData\Local\Temp\ipykernel_19372\1196713534.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,Municípios e respectivas\nUnidades da Federação,Posição ocu-\npada pelos\n100 maiores\nmunicípios,Produto Interno Bruto\na preços correntes\n(1 000 R$),Participação (%),Participação\nacumulada (%)
0,São Paulo (SP),1º,748 759 007,"9,84","9,84"
1,Rio de Janeiro (RJ),2º,331 279 902,"4,35","14,19"
2,Brasília (DF),3º,265 847 334,"3,49","17,69"
3,Belo Horizonte (MG),4º,97 509 893,"1,28","18,97"
4,Manaus (AM),5º,91 768 773,"1,21","20,17"
...,...,...,...,...,...
95,Americana (SP),96º,12 078 627,"0,16","52,29"
96,Paranaguá (PR),97º,12 069 503,"0,16","52,45"
97,Chapecó (SC),98º,11 954 532,"0,16","52,61"
98,São Francisco do Conde (BA),99º,11 926 908,"0,16","52,76"
99,Rio Verde (GO),100º,11 872 211,"0,16","52,92"